### ISSUE TITLE
Recent WOLTK update appears to cause TBC-Talented saved data corruption

### ISSUE THREAD

**Issue by KevinTyrrell** [Lethay/TalentedClassic#65] opened 2022-08-25 05:09 UTC
Recently a push was made for a WOTLK update to talented. WoWUp indicated TalentedClassic was out of date (somehow it didn't recognize the update as non-TBC) and naturally it updated when I pressed `Update All`. In doing so, it installed the WOTLK version onto the TBC client. Upon logging in, I noticed a barrage of errors, removed TalentedClassic, then re-installed TalentedClassic's TBC version from two months ago.

However it appears damage had been done to my `SavedVariables` file, as loading in with my old `Talented.lua` and `Talented_Data.lua` in `/SavedVariables/` yields the following below. Deleting my old `SavedVariables` files and letting TalentedClassic create new ones solves the issue, but results in the loss of my templates (I can probably retrieve those in the lua files without too much of an issue).

Talented Version: v211202
Talented_Data Version: `20502`, Expected Build: `"2.5.2 - 40892 - Nov 1 2021 - 20502"`

Error Trace(s):

```lua
4x Talented\core.lua:465: assertion failed!
[string "=[C]"]: in function `assert'
[string "@Talented\core.lua"]:465: in function `LoadTemplates'
[string "@Talented\core.lua"]:81: in function <Talented\core.lua:78>
[string "=[C]"]: ?
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...ceDetails\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <...ceDetails\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>
```

```lua
2x Talented\view-View.lua:100: attempt to index local 'first_tree' (a nil value)
[string "@Talented\view-View.lua"]:100: in function `SetClass'
[string "@Talented\view-View.lua"]:162: in function `SetTemplate'
[string "@Talented\core.lua"]:271: in function `SetTemplate'
[string "@Talented\core.lua"]:367: in function `Update'
[string "@Talented\core.lua"]:350: in function <Talented\core.lua:347>
[string "=(tail call)"]: ?
[string "TOGGLETALENTS"]:1: in function <[string "TOGGLETALENTS"]:1>
```

Chat Output: https://gist.github.com/KevinTyrrell/ceb3c59b405280585046b0e06f216c3d

Talented Frame:

![image](https://user-images.githubusercontent.com/12791400/186578906-48fc1dff-e3ab-4588-b718-42838ff29c7e.png)

SavedVariable Files

[Talented & Talented_Data - Corrupted SavedVariables.zip](https://github.com/Lethay/TalentedClassic/files/9421502/Talented.Talented_Data.-.Corrupted.SavedVariables.zip)

**Comment by DragunovUA** [comment] 2022-08-28 09:04
same for me, after latest update addon not working properly. not a big deal ofc, cos prepatch in few days

**Comment by glajchs** [comment] 2022-08-28 20:54
I think, at most, we could try and write something to recognize the fact that it's trying to load templates for the old expansion and stop loading then.  It would prevent corruption.
As DragunovUA noted, these BC talents will be unusable in a few days, though again I think when that happens we should make a "nice" way to wipe the old talents.

I propose keeping the Template _names_ but emptying the templates themselves.
That way when you logon, you'll still have your "Discipline", "Holy", and "PvP" templates by name, but their contents will be empty and ready to fill out (instead of listed as corrupt and making you re-make the template names for each class/spec you have)

**Comment by Lethay** [comment] 2022-09-04 01:31
This was caused by the last release having the interface ID as an old one, from TBC classic. Although I marked it as WotLK myself, one or more of the addon repositories scanned it as a TBC addon, hence these issues.
As TBC no longer exists (again), I suppose this isn't a problem anymore, so will close it for now

**Closed by Lethay** 2022-09-04 01:31 UTC
