### ISSUE TITLE
wotlk - unable to "set role"

### ISSUE THREAD

**Issue by sofar** [Lethay/TalentedClassic#69] opened 2022-08-31 19:43 UTC
The in-game talent window has a clickable icon that allows the player to designate their role as "tank", "dps" or "healer".

Other addons rely on this setting to designate tank frames and other functionality (group finder).

Talented has no way of reaching this UI element for the user. This forces the player to disable talented to change their role.

A complication is that the default role seems to be "tank" for everyone. This makes tank frames difficult to use in raids. If talented could incorporate this (per-spec, so one for each primary or secondary talent pages), it would greatly help.

**Comment by Lethay** [comment] 2022-09-01 11:31
Huh. I had no idea that this was a thing. It wasn't in the original WotLK release! I'll get to it when I next have free time, perhaps this weekend.

**Comment by Lethay** [comment] 2022-09-04 01:28
Just FYI, I haven't got any bright ideas for how to do this, at the moment. It's sitting on the "to-do"

**Comment by hexvenn** [comment] 2022-09-13 18:47
Is it possible to add a button to bring up blizzard talent frame? Then we can select the default role that way.

**Comment by KufrA** [comment] 2022-10-12 21:31
I also would like to access the new special button. Is it possible taking a GUI element from another window and adding it to your addon? If that does not work, then as hexvenn sugguested, a way to view the normal talent window using some button somewhere.

**Comment by Lethay** [comment] 2022-10-12 21:44
I now know what to do to fix it, but the issue is time. I haven't logged in since WotLK's release because I don't have free time at the moment. But it will be done.

**Comment by Lethay** [comment] 2022-12-05 23:25
Hopefully fixed with today's release, let me know, as I'm not sure what it's meant to look like 🙃

**Comment by Lethay** [comment] 2022-12-05 23:27
![image](https://user-images.githubusercontent.com/5658454/205765537-034f0598-690c-4835-9299-9be86cefd047.png)
That is, you can select a role and it will call SetTalentGroupRole, such that GetTalentGroupRole() reports correctly. Whether this is doing all the correct things behind the scene with group finder, I'm none the wiser.

**Closed** 2023-09-10 09:33 UTC
Labels: enhancement
